-- ConnectSphere schema for Supabase Postgres.
-- Run this in the Supabase SQL editor (once per project).
-- The Express API uses the service role key, which bypasses RLS.

create table if not exists organisations (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  industry varchar(80),
  contact_email varchar(160),
  phone varchar(40),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists users (
  id bigint generated by default as identity primary key,
  email varchar(160) not null unique,
  password_hash varchar(255) not null,
  full_name varchar(160) not null,
  phone varchar(40),
  organisation_id bigint references organisations(id) on delete set null,
  department varchar(120),
  communication_preference varchar(32) not null default 'IN_APP',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists user_roles (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  role varchar(40) not null,
  unique (user_id, role)
);

create table if not exists venues (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  location varchar(255),
  capacity integer not null default 0,
  facilities text,
  accessibility text,
  operating_hours varchar(120),
  setup_minutes integer not null default 30,
  teardown_minutes integer not null default 30,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists venue_layouts (
  id bigint generated by default as identity primary key,
  venue_id bigint not null references venues(id) on delete cascade,
  layout varchar(80) not null,
  unique (venue_id, layout)
);

create table if not exists venue_unavailability (
  id bigint generated by default as identity primary key,
  venue_id bigint not null references venues(id) on delete cascade,
  reason varchar(255) not null,
  start_at timestamptz not null,
  end_at timestamptz not null,
  created_by bigint references users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists equipment (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  type varchar(80) not null default 'GENERAL',
  description text,
  quantity integer not null default 1,
  location varchar(160),
  status varchar(40) not null default 'AVAILABLE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists events (
  id bigint generated by default as identity primary key,
  organisation_id bigint references organisations(id) on delete set null,
  organiser_id bigint references users(id) on delete set null,
  coordinator_id bigint references users(id) on delete set null,
  cloned_from_event_id bigint references events(id) on delete set null,
  name varchar(200) not null,
  description text,
  purpose varchar(255),
  category varchar(80) not null default 'OTHER',
  status varchar(40) not null default 'DRAFT',
  start_at timestamptz,
  end_at timestamptz,
  expected_attendance integer,
  accessibility_needs text,
  layout_preference varchar(80),
  venue_requirements text,
  equipment_notes text,
  special_requests text,
  registration_required boolean not null default false,
  registration_opens_at timestamptz,
  registration_closes_at timestamptz,
  registration_capacity integer,
  registration_open boolean not null default false,
  rejection_reason text,
  operational_notes text,
  venue_ready boolean not null default false,
  equipment_ready boolean not null default false,
  sub_state varchar(40),
  review_remarks text,
  clarification_response text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists events_status_idx on events (status);
create index if not exists events_sub_state_idx on events (sub_state);
create index if not exists events_start_at_idx on events (start_at);

create table if not exists event_status_history (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  actor_id bigint references users(id),
  from_status varchar(40),
  to_status varchar(40) not null,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists event_sessions (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  title varchar(200) not null,
  start_at timestamptz,
  end_at timestamptz,
  session_type varchar(80),
  notes text
);

create table if not exists event_comments (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  author_id bigint not null references users(id),
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists event_documents (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  uploaded_by bigint references users(id),
  file_name varchar(255) not null,
  file_path varchar(500) not null,
  mime_type varchar(120),
  created_at timestamptz not null default now()
);

create table if not exists venue_bookings (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  venue_id bigint not null references venues(id),
  requested_by bigint references users(id),
  decided_by bigint references users(id),
  status varchar(40) not null default 'PENDING',
  start_at timestamptz not null,
  end_at timestamptz not null,
  setup_minutes integer not null default 30,
  teardown_minutes integer not null default 30,
  notes text,
  decision_reason text,
  alternative_suggestion text,
  decided_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists equipment_requests (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  equipment_id bigint references equipment(id) on delete set null,
  quantity integer not null default 1,
  notes text,
  status varchar(40) not null default 'PENDING',
  requested_by bigint references users(id),
  decided_by bigint references users(id),
  decision_reason text,
  decided_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists equipment_reservations (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  equipment_id bigint not null references equipment(id) on delete cascade,
  quantity integer not null default 1,
  status varchar(40) not null default 'RESERVED',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists registrations (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  attendee_id bigint not null references users(id) on delete cascade,
  status varchar(40) not null default 'REGISTERED',
  waitlist_position integer,
  withdrawn_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  event_id bigint references events(id) on delete set null,
  type varchar(80) not null,
  title varchar(200) not null,
  body text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  actor_id bigint references users(id),
  action varchar(80) not null,
  entity_type varchar(80) not null,
  entity_id bigint,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create table if not exists coordinator_reassignments (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  from_coordinator_id bigint references users(id),
  to_coordinator_id bigint references users(id),
  status varchar(40) not null default 'PENDING',
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table organisations enable row level security;
alter table users enable row level security;
alter table user_roles enable row level security;
alter table venues enable row level security;
alter table venue_layouts enable row level security;
alter table venue_unavailability enable row level security;
alter table equipment enable row level security;
alter table events enable row level security;
alter table event_status_history enable row level security;
alter table event_sessions enable row level security;
alter table event_comments enable row level security;
alter table event_documents enable row level security;
alter table venue_bookings enable row level security;
alter table equipment_requests enable row level security;
alter table equipment_reservations enable row level security;
alter table registrations enable row level security;
alter table notifications enable row level security;
alter table audit_logs enable row level security;
alter table coordinator_reassignments enable row level security;
