const ROLES = {
  EVENT_ORGANISER: 'EVENT_ORGANISER',
  EVENT_COORDINATOR: 'EVENT_COORDINATOR',
  // SCRUM-71 AC6: only a Lead may assign a Coordinator. Overlaps SCRUM-54.
  EVENT_COORDINATOR_LEAD: 'EVENT_COORDINATOR_LEAD',
  VENUE_STAFF: 'VENUE_STAFF',
  TECHNICAL_SUPPORT: 'TECHNICAL_SUPPORT',
  ATTENDEE: 'ATTENDEE',
};

const ALL_ROLES = Object.values(ROLES);

const INTERNAL_ROLES = [
  ROLES.EVENT_COORDINATOR,
  ROLES.EVENT_COORDINATOR_LEAD,
  ROLES.VENUE_STAFF,
  ROLES.TECHNICAL_SUPPORT,
];

module.exports = { ROLES, ALL_ROLES, INTERNAL_ROLES };
